### ISSUE TITLE
Attribute source type 'Sender' supported for product service?

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohNet#29]
The [wiki](http://wiki.openhome.org/wiki/Av:Developer:ProductService) for the Product service says that the following source types are supported:

- Playlist
- Radio
- Receiver 
- UpnpAv
- NetAux
- Analog
- Digital
- Hdmi

The [wiki](http://wiki.openhome.org/wiki/Av:Developer:SenderService) for the Sender service says:

> If a device's Product service reports an attribute source of type 'Sender', then that device is guaranteed to bear the Sender service.

Does the Product service supports an attribute source of type 'Sender'?

**Comment by SimonChisholm** [comment]
Yes, the Attributes state variable in the Product service can contain "Sender".
This is independent of the source types as reported by Product's ServiceXml.  (In general, ServiceXml and Attributes can be used together to infer the presence of all other OpenHome services).

(Note that this issue is not related to ohNet.  It is relevant to ohPipeline.  If you're concerned with behaviour of upmpdcli, that'd be solely an issue for that application)

**Comment by joerg-krause** [comment]
Did you mean 'SourceXml' instead of 'ServiceXml'?

So "Sender" is a supported value of 'Attributes' whereas "Receiver" is a supported value of the source type in "SourceXml", right?

**Comment by SimonChisholm** [comment]
Sorry, yes, 'SourceXml' it is.

Your understanding of how to infer the presence of Sender and Receiver is correct.

**Comment by joerg-krause** [comment]
Thanks!
